apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter-config
  namespace: monitoring
data:
  snmp.yml: |
    modules:
      mikrotik:
        walk: [1.3.6.1.2.1.2.2.1]
      cisco:
        walk: [1.3.6.1.2.1.2.2.1]
      wifi_router:
        walk: [1.3.6.1.2.1.2.2.1]
